[versions]
lombokVersion="1.18.36"
quarkusVersion="3.16.2"

[libraries]
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombokVersion" }
quarkus= { group = "io.quarkus.platform", name = 'quarkus-bom', version.ref = "quarkusVersion" }