name: Build
on:
  - push
  - release
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - name : chown
        run: chmod +x gradlew
      - name: Execute Gradle build
        run: ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true
        env:
          QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}  
          QUARKUS_CONTAINER_IMAGE_GROUP: arnaudroubinet
          QUARKUS_CONTAINER_IMAGE_NAME: krabotnotif
          QUARKUS_CONTAINER_IMAGE_TAG: latest,snapshot
