name: Build
on:
  - push
  - workflow_dispatch
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'

      - name : Set executable permissions for maven
        run: chmod +x ./mvnw

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Execute maven install
        run: ./mvnw install
        env:
          QUARKUS_NATIVE_ENABLE_HTTPS_URL_HANDLER: true

      - name: Build multi-arch Docker images
        run: |
          docker buildx create --name multiarch --use || true
          docker buildx build --platform linux/amd64,linux/arm64 \
            -f src/main/docker/Dockerfile.jvm \
            -t krabotnotif-jvm:latest \
            --push .
          docker buildx build --platform linux/amd64,linux/arm64 \
            -f src/main/docker/Dockerfile.native \
            -t krabotnotif-native:latest \
            --push .