# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Build app and publish to docker
on: push

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout app
      - uses: actions/setup-java@v2
        with:
          java-version: 15
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v1
        name: Build app
        with:
          gradle-version: current
          arguments: clean bootJar
