name: Build
on:
  - push
  - release
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo step
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - uses: gradle/gradle-build-action@v2.4.2
        env:
          QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          QUARKUS_CONTAINER_IMAGE_IMAGE: arnaudroubinet/krabotnotif:snapshot
          QUARKUS_CONTAINER_IMAGE_PUSH: true
          QUARKUS_DOCKER_BUILDX_PLATFORM: linux/arm64
        with:
          gradle-version: current
          arguments: build -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.container-image.push=true --scan