name: Build
on:
  - push
  - release
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradle build -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true
        env:
          QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}  
          QUARKUS_CONTAINER_IMAGE_GROUP: arnaudroubinet
          QUARKUS_CONTAINER_IMAGE_NAME: krabotnotif
          QUARKUS_CONTAINER_IMAGE_TAG: latest,snapshot
