name: scanning

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - "src/**"
      - "pom.xml"
  schedule:
    - cron: "30 1 * * 1"

permissions:
  security-events: write

jobs:
  codeql:
    runs-on: ubuntu-latest
    steps:
      - name: jdk21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "adopt"
      - name: codeql init
        uses: github/codeql-action/init@v2
        with:
          languages: java
      - name: checkout
        uses: actions/checkout@v3
      - name: gradle compile
        run: ./gradlew clean build
      - name: codeql analyze
        uses: github/codeql-action/analyze@v2
