name: Vulnerability Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  scan:
    name: Daily Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Pull docker image
        run: docker pull arnaudroubinet/krabotnotif:latest

      - uses: lazy-actions/gitrivy@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: arnaudroubinet/krabotnotif:latest
          trivy_version: "0.22.0"
